# Generated by Django 3.1 on 2020-08-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='fb_link',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
