# Generated by Django 3.1 on 2020-08-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0003_auto_20200817_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='fb_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
