# Generated by Django 3.1 on 2020-09-08 11:32

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0004_auto_20200817_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('Placements', 'Placements'), ('Achivements', 'Achivements'), ('Examinations', 'Examinations'), ('Scholarships', 'Scholarships'), ('Activities', 'Activities'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
