# Generated by Django 3.1 on 2020-11-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0005_auto_20200908_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
